"""Shared utilities for Kyzlo Swarm agents."""

from .config import settings, DOMAINS, DomainConfig
from .llm_client import LLMClient, get_queen_client, get_orchestrator_client, get_worker_client
from .agent_mail import AgentMailClient, Message
from .bridge import Bridge, BridgeClient, BridgeMessage, Signals
from .rag_client import RAGBrainClient, rag_client
from .base_agent import SwarmAgent, run_agent
from .status_survey import StatusSurveySystem
from .comm_laws import (
    RevokedAgent,
    RevokedAgentsRegistry,
    revoked_registry,
    REVOKED_AGENTS_FILE,
    HUMAN_ALERTS_DIR,
    COMMUNICATION_LAWS,
    EXEMPT_CHANNELS,
    VIOLATION_LOG_FILE,
    validate_message,
    validate_and_log,
    get_violations_report,
    clear_violations,
    parse_agent_identity,
    identity_resolver,
    CommViolation,
    read_violations_from_log,
    get_violation_stats_from_log,
)
from .schemas import (
    TaskType,
    FrictionType,
    DeliverableType,
    MemoryCategory,
    ValidationStatus,
    QAStatus,
    AgentRole,
    DomainType,
    ConstraintEnvelope,
    TaskAssignment,
    TaskSlice,
    Deliverable,
    Metrics,
    FeedbackBlock,
    WorkerOutput,
    Violation,
    ValidationResult,
    MergedResult,
    QAReport,
    MemoryRecord,
    FeedbackSummary,
    RuleAdjustment,
    EscalationRequest,
    EscalationDecision,
    TaskRecord,
    AgentStatusReport,
)

__all__ = [
    # Config
    "settings",
    "DOMAINS",
    "DomainConfig",
    # Clients
    "LLMClient",
    "AgentMailClient",
    "Message",
    "Bridge",
    "BridgeClient",
    "BridgeMessage",
    "Signals",
    "RAGBrainClient",
    "rag_client",
    # Base
    "SwarmAgent",
    "run_agent",
    # Survey
    "StatusSurveySystem",
    # Communication Laws
    "COMMUNICATION_LAWS",
    "EXEMPT_CHANNELS",
    "VIOLATION_LOG_FILE",
    "validate_message",
    "validate_and_log",
    "get_violations_report",
    "clear_violations",
    "parse_agent_identity",
    "identity_resolver",
    "CommViolation",
    "read_violations_from_log",
    "get_violation_stats_from_log",
    "RevokedAgent",
    "RevokedAgentsRegistry",
    "revoked_registry",
    "REVOKED_AGENTS_FILE",
    "HUMAN_ALERTS_DIR",
    "SURVIVAL_NOTICE_TEMPLATE",
    "get_survival_notice",
    "check_agent_alive",
    "get_agent_violation_count",
    # Schemas
    "TaskType",
    "FrictionType",
    "DeliverableType",
    "MemoryCategory",
    "ValidationStatus",
    "QAStatus",
    "ConstraintEnvelope",
    "TaskAssignment",
    "TaskSlice",
    "Deliverable",
    "Metrics",
    "FeedbackBlock",
    "WorkerOutput",
    "Violation",
    "ValidationResult",
    "MergedResult",
    "QAReport",
    "MemoryRecord",
    "FeedbackSummary",
    "RuleAdjustment",
    "EscalationRequest",
    "EscalationDecision",
    "TaskRecord",
    "AgentRole",
    "DomainType",
    "AgentStatusReport",
]
